# Default values for kuiper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


replicaCount: 1

image:
  repository: lfedge/ekuiper
  pullPolicy: IfNotPresent


service:
  # -- service type
  type: ClusterIP

  # -- Service ports
  ports:
    restapi:
      # -- eKuiper restapi port name
      name: "restapi"
      # -- eKuiper restapi port
      port: 9081
    pushapi:
      # -- eKuiper pushapi port name
      name: "pushapi"
      # -- eKuiper pushapi port
      port: 10081


  # -- Specify the nodePort(s) value for the LoadBalancer and NodePort service types.
  # ref: https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport
  nodePorts:
    restapi:
    pushapi:
  ## Set the LoadBalancer service type to internal only.
  ## ref: https://kubernetes.io/docs/concepts/services-networking/service/#internal-load-balancer
  ##
  # loadBalancerIP:
  ## Load Balancer sources
  ## ref: https://kubernetes.io/docs/tasks/access-application-cluster/configure-cloud-provider-firewall/#restrict-access-for-loadbalancer-service
  ## Example:
  ## loadBalancerSourceRanges:
  ## - 10.10.10.0/24
  ##
  # @ignored
  loadBalancerSourceRanges: []
  ## TODO: it's just for OpenELB
  # -- Provide any additional annotations which may be required. Evaluated as a template
  annotations:
    lb.kubesphere.io/v1alpha1: openelb
    eip.openelb.kubesphere.io/v1alpha2: eip-pool
    protocol.openelb.kubesphere.io/v1alpha1: layer2

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  ## TODO: not all storage class can work well, it depends on the specific storage
  storageClass: standard
  # storageClass: huawei-nfs

ekuiperMounts:
  - name: pvc-ekuiper-data
    capacity: 100Mi
    mountPath: "/kuiper/data"
  - name: pvc-ekuiper-plugins-portable
    capacity: 100Mi
    mountPath: "/kuiper/plugins/portable"

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations:
  - key: "node.kubernetes.io/not-ready"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30
  - key: "node.kubernetes.io/unreachable"
    operator: "Exists"
    effect: "NoExecute"
    tolerationSeconds: 30

affinity: {}

# -- clusterDomain Kubernetes Cluster Domain
clusterDomain: cluster.local

# -- Enable encryption to eKuiper
tls:
  # -- tls.enabled Enable TLS support on eKuiper
  enabled: false
  # -- tls.autoGenerated Generate automatically self-signed TLS certificates
  autoGenerated: false
  # -- tls.caCertificate Certificate Authority (CA) bundle content
  caCertificate: |-
  # - tls.serverCertificate Server certificate content
  serverCertificate: |-
  # - tls.serverKey Server private key content
  serverKey: |-
  # - tls.existingSecret Existing secret with certificate content to eKuiper credentials
  existingSecret: ""
  # - tls.existingSecretFullChain Whether or not the existing secret contains the full chain in the certificate (`tls.crt`). Will be used in place of `ca.cert` if `true`.
  existingSecretFullChain: false


# -- remove this when the mqtt_source configmap is available
ekuiperEnv:
  enabled: true
  keys:
    mqttDefaultServer: MQTT_SOURCE__DEFAULT__SERVER
    prometheusEnabled: KUIPER__BASIC__PROMETHEU
    premetheusPort: KUIPER__BASIC__PROMETHEUSPORT
    fileLog: KUIPER__BASIC__FILELOG

  values:
    mqttDefaultServer: tcp://broker.emqx.io:1883
    prometheusEnabled: true
    premetheusPort: 9081
    fileLog: false
