apiVersion: v1
kind: Service
metadata:
  name: {{ include "ekuiper.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ekuiper.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "LoadBalancer" }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- end }}
  ports:
  - name: {{ .Values.service.ports.restapi.name }}
    port:  {{ .Values.service.ports.restapi.port | default 9081 }}
    protocol: TCP
    targetPort:  restapi
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.restapi)) }}
    nodePort: {{ .Values.service.nodePorts.restapi }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  - name: {{ .Values.service.ports.pushapi.name }}
    port: {{ .Values.service.ports.pushapi.port | default 10081 }}
    protocol: TCP
    targetPort: pushapi
    {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) (not (empty .Values.service.nodePorts.pushapi)) }}
    nodePort: {{ .Values.service.nodePorts.pushapi }}
    {{- else if eq .Values.service.type "ClusterIP" }}
    nodePort: null
    {{- end }}
  selector:
    {{- include "ekuiper.selectorLabels" . | nindent 4 }}
